# Generated by Django 5.0.1 on 2024-04-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=100),
        ),
    ]
