# Generated by Django 5.0.1 on 2024-06-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
